export const GET_TRADE = 'GET_TRADE'
export const GET_TRADE_SUCCESS = 'GET_TRADE_SUCCESS'
export const GET_TRADE_FAILURE = 'GET_TRADE_FAILURE'

export const GET_MARKETS = 'GET_TRADE'
export const GET_MARKETS_SUCCESS = 'GET_MARKETS_SUCCESS'
export const GET_MARKETS_FAILURE = 'GET_MARKETS_FAILURE'